-- liquibase formatted sql

-- changeset mschechin:1
CREATE TABLE notification_task
(
    id             BIGINT generated by default as identity primary key,
    chat_id        BIGINT    NOT NULL,
    message        TEXT      NOT NULL,
    date_time_send TIMESTAMP NOT NULL
);
